### PR TITLE
Two more tests

### PR DESCRIPTION
**Pull request by josephwoodward**

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
Hold up, I think I have fixed the same ones locally :) I should have them all fixed in about 20-30 mins (am just removing the base classes entirely right now, rest of the tests are fixed)

**Comment by JakeGinnivan** [comment]
Quick question, ShouldBePositive fails on 0. Would you consider 0 positive?

**Comment by JakeGinnivan** [comment]
Sorry about wasting your effort. have pushed my latest changes. Down to 23 fails, most should be easy

**Comment by josephwoodward** [comment]
No problem, it was bound to happen at some point. 23 failing left now? good job!

I wouldn't consider 0 positive (or negative for that matter), so would expect it to fail on a ShouldBePositive test.

**Pull request closed without merging**
